todo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^todo/', include('todoapp.urls')),
]

todoapp/urls.py
from django.conf.urls import url
from .views import (HomeView, CreateUpdateTodoView, DeleteTodoView,
                    CompleteTodoView, CreateLabelView,)


app_name = 'todoapp'
urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^new$', CreateUpdateTodoView.as_view(), name='new_todo'),
    url(r'^(?P<pk>[0-9]+)/edit$',
        CreateUpdateTodoView.as_view(),
        name='edit_todo'),
    url(r'^(?P<pk>[0-9]+)/delete$',
        DeleteTodoView.as_view(),
        name='delete_todo'),
    url(r'^(?P<pk>[0-9]+)/complete$',
        CompleteTodoView.as_view(),
        name='complete_todo'),
    url(r'^new_label$', CreateLabelView.as_view(), name='new_label'),
]

todoapp/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _


class Label(models.Model):
    """Model that defines app labels."""

    name = models.CharField(max_length=150)
    slug = models.SlugField(max_length=150, unique=True, editable=False)

    def raise_validation_error(self, value):
        raise ValidationError(_("This label already exists."))

    def clean(self):
        self.slug = slugify(self.name)

        if Label.objects.filter(slug=self.slug).exists():
            # If pk exists, object exists in db and is being edited by user.
            if self.pk:
                try:
                    self.validate_unique()
                except ValidationError:
                    self.raise_validation_error(self.slug)
            else:
                self.raise_validation_error(self.slug)

    def save(self, *args, **kwargs):
        self.clean()
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class TodoList(models.Model):
    """Core model of the app defining the ToDo list."""

    title = models.CharField(max_length=150, unique=True)
    details = models.TextField(blank=True)
    due_date = models.DateField(blank=True, null=True)
    label = models.ForeignKey(Label)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    objects = models.Manager()

    PENDING = 'Pending'
    COMPLETED = 'Completed'
    MISSED = 'Missed'
    STATUS_CHOICES = (
        (PENDING, PENDING),
        (COMPLETED, COMPLETED),
        (MISSED, MISSED),
    )

    status = models.CharField(max_length=50, choices=STATUS_CHOICES,
                              default=PENDING)

    def __str__(self):
        return self.title

todoapp/forms.py
from django import forms
from django.forms import ModelForm

from .models import TodoList, Label


class SearchForm(forms.Form):
    q = forms.CharField(max_length=255)


class DateInput(forms.DateInput):
    input_type = 'date'


class TodoForm(ModelForm):

    class Meta:
        model = TodoList
        fields = ['title', 'details', 'due_date', 'label', 'status']
        widgets = {
            'due_date': DateInput(),
            'details': forms.Textarea(
                attrs={'class': 'materialize-textarea'}
            )
        }

class LabelForm(ModelForm):

    class Meta:
        model = Label
        fields = ['name']

todoapp/views.py
from datetime import datetime

from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.db.models import Q
from django.urls import reverse

from .models import Label, TodoList
from .forms import SearchForm, TodoForm, LabelForm


def sort_todolists(todolists):
    lists_with_due_date = []
    lists_without_due_date = []

    for todolist in todolists:
        if todolist.due_date:
            lists_with_due_date.append(todolist)
        else:
            lists_without_due_date.append(todolist)

    lists_with_due_date.sort(key=lambda todolist: todolist.due_date)
    lists_without_due_date.sort(key=lambda todolist: todolist.date_created)

    return lists_with_due_date + lists_without_due_date


class HomeView(View):

    def get(self, request):
        labels = Label.objects.all()
        todo_lists = TodoList.objects.all()

        selected_label = request.GET.get('label')
        if selected_label:
            todo_lists = todo_lists.filter(label__name=selected_label)

        q = request.GET.get('q')
        if q:
            form = SearchForm(request.GET)
            if form.is_valid():
                q = form.cleaned_data.get('q')
                todo_lists = todo_lists.filter(Q(title__icontains=q) |
                                               Q(details__icontains=q) |
                                               Q(label__name__icontains=q)
                                               )

        pending_todos = todo_lists.filter(status=TodoList.PENDING)
        skipped_todos = pending_todos.filter(due_date__isnull=False,
                                             due_date__lt=datetime.now())
        # Update skipped todos to missed
        skipped_todos.update(status=TodoList.MISSED)
        missed_todos = todo_lists.filter(status=TodoList.MISSED)
        completed_todos = todo_lists.filter(status=TodoList.COMPLETED)

        todos_by_status = [
            {'status': TodoList.PENDING, 'todos': sort_todolists(pending_todos)},
            {'status': TodoList.COMPLETED, 'todos': sort_todolists(completed_todos)},
            {'status': TodoList.MISSED, 'todos': sort_todolists(missed_todos)}
        ]

        context = {
            'labels': labels,
            'todos_by_status': todos_by_status
        }
        return render(request, 'todoapp/home.html', context)


class CreateUpdateTodoView(View):

    def get(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        form = TodoForm()

        if pk is not None:
            todo = get_object_or_404(TodoList, pk=pk)
            form = TodoForm(instance=todo)

        context = {
            'form': form
        }
        return render(request, 'todoapp/create_edit.html', context)

    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')

        if pk is not None:
            todo = get_object_or_404(TodoList, pk=pk)
            form = TodoForm(request.POST, instance=todo)
        else:
            form = TodoForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect(reverse('todoapp:home'))

        context = {
            'form': form
        }

        return render(request, 'todoapp/create_edit.html', context)


class DeleteTodoView(View):

    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')

        todo = get_object_or_404(TodoList, pk=pk)
        todo.delete()
        return redirect(reverse('todoapp:home'))


class CompleteTodoView(View):

    def get(self, request, *args, **kwargs):
        pk = kwargs.get('pk')

        todo = get_object_or_404(TodoList, pk=pk)

        todo.status = TodoList.COMPLETED
        todo.save()
        return redirect(reverse('todoapp:home'))


class CreateLabelView(View):

    def get(self, request):
        form = LabelForm()

        context = {'form': form}
        return render(request, 'todoapp/create_label.html', context)

    def post(self, request, *args, **kwargs):
        form = LabelForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect(reverse('todoapp:new_todo'))

        context = {
            'form': form
        }
        return render(request, 'todoapp/create_label.html', context)

templates/base.html
{% load staticfiles %}
<html>
<head>
    <title>ToDo app</title>
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'css/home.css' %}" type="text/css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>
    {% block content %}
    {% endblock %}
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</body>
</html>

todoapp/templates/todoapp/create_edit.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'todoapp:home' %}">Home</a>
    <div class="row">
         <div class="col s6">
            <form action="" method="POST">
                {% csrf_token %}
                {% for field in form %}
                    <div class="input-field">
                        {% if field.name == "status" %}
                            <select name="status">
                                {% for choice_label, value in form.fields.status.choices %}
                                    {% if value != "Missed" %}
                                        <option value="{{ value }}">{{ choice_label }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        {% elif field.name == "label" %}
                            <select name="label">
                                {% for label_id, label_name in form.fields.label.choices %}
                                    <option value="{{ label_id }}">{{ label_name }}</option>
                                {% endfor %}
                            </select>
                            <a href="{% url 'todoapp:new_label' %}" class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">add</i></a>
                        {% else %}
                            {{ field }}
                        {% endif %}
                        <label for="{{ field.id_for_label }}" {% if field.name == "due_date" %} class="date-label" {% endif %}>{{ field.label }}</label>
                    </div>
                {% endfor %}
                <button class="btn waves-effect waves-light" type="submit" name="submit_form">Submit
                    <i class="material-icons right">send</i>
                </button>
            </form>
        </div>
    </div>
{% endblock %}

todoapp/templates/todoapp/create_label.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <button class="btn waves-effect waves-light" type="submit" name="submit_form">Submit
            <i class="material-icons right">send</i>
        </button>
    </form>
{% endblock content %}

todoapp/templates/todoapp/home.html
{% extends 'base.html' %}

{% block content %}
{# <div class="container"> #}
    <a href="{% url 'todoapp:new_todo' %}" class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">add</i></a>
    <form action="{% url 'todoapp:home' %}" method="get">
        <div class="row">
            <div class="input-field col s6">
                <input type="search" name="q">
                <label for="icon_prefix">Search</label>
            </div>
        </div>
    </form>

    <p>Labels</p>
    <ul>
        <li><a href="{% url 'todoapp:home' %}" class="chip">All</a></li>
        {% for label in labels %}
            <li><a href="?label={{ label.slug }}" class="chip">{{ label }}</a></li>
        {% empty %}
            <p>Add new label</p>
        {% endfor %}
    </ul>

    <div class="row">
        {% for item in todos_by_status %}
            {% include "todoapp/todo_status_snippet.html" with status=item.status status_todos=item.todos %}
        {% endfor %}
    </div>
{# </div> #}
{% endblock %}

todoapp/templates/todoapp/todo_status_snippet.html
<div class="col s6 m3">
    <p> {{ status|title }} TODOs</p>
    {% for todo in status_todos %}
        <div class="card">
            <div class="card-content">
                <a href="?label={{ todo.label.slug }}" class="chip">{{ todo.label.name }}</a>
                <span class="card-title activator grey-text text-darken-4">{{ todo.title }}<i class="material-icons right">more_vert</i></span>
                <p>{% if todo.due_date %}Due date: {{ todo.due_date }}{% endif %}</p>
                <p><a href="{% url 'todoapp:edit_todo' todo.pk %}">Edit</a></p>
                <p><form action="{% url 'todoapp:delete_todo' todo.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" name="delete" value="Delete">
                </form></p>
                {% if status == 'Pending' %}
                    <p><a href="{% url 'todoapp:complete_todo' todo.pk %}">mark complete</a></p>
                {% endif %}
            </div>
            <div class="card-reveal">
                <span class="card-title grey-text text-darken-4">{{ todo.title }}<i class="material-icons right">close</i></span>
                <p>{{ todo.details }}</p>
            </div>
        </div>
    {% empty %}
        <p>No {{ status|lower }} ToDO</p>
    {% endfor %}
</div>